import { StyleSheet } from 'react-native';
import { colours, elevation, fontFaces, fontSizes, layout, radii, spacing } from '@/shared/ui/theme';

export const styles = StyleSheet.create({
  scroll: {
    flex: 1,
  },
  container: {
    paddingHorizontal: layout.screenPadding,
    paddingBottom: spacing['3xl'],
  },
  fixedTabs: {
    // Full-width pinned header above the scroll view. The horizontal padding matches the
    // scroll content's; the underline tab strip's own negative margin bleeds its bottom
    // border edge-to-edge, exactly as before — but the tabs are now always tappable.
    paddingHorizontal: layout.screenPadding,
    backgroundColor: colours.background,
  },
  tabControl: {
    marginHorizontal: 0,
  },
  financialDisclaimer: {
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
  },
  tabPanel: {
    marginTop: spacing.xs,
  },
  mortgageSummaryPanel: {
    gap: spacing.lg,
    marginBottom: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingTop: spacing.md,
    paddingBottom: spacing.lg,
  },
  summaryHeader: {
    position: 'relative',
    alignItems: 'center',
    paddingHorizontal: 44,
    minHeight: 62,
  },
  summaryHeaderCopy: {
    alignItems: 'center',
    minWidth: 0,
  },
  summaryTitle: {
    ...fontFaces.heading.bold,
    fontSize: fontSizes.xl,
    lineHeight: 32,
    color: colours.primary,
    textAlign: 'center',
  },
  summaryCategoryTag: {
    alignSelf: 'center',
    marginTop: spacing.xxxs,
  },
  summaryPinButton: {
    position: 'absolute',
    top: 0,
    right: 0,
  },
  summaryRaisedPanel: {
    borderRadius: radii.chip,
    backgroundColor: colours.white,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.lg,
    ...elevation.level2,
  },
  summaryMetricRow: {
    minHeight: 66,
    justifyContent: 'center',
  },
  summaryMetricLabel: {
    ...fontFaces.body.regular,
    fontSize: fontSizes.md,
    lineHeight: 22,
    color: colours.textSecondary,
    marginBottom: spacing.xxs,
  },
  summaryMetricValue: {
    ...fontFaces.heading.bold,
    fontSize: fontSizes.lg,
    lineHeight: 25,
    color: colours.primary,
  },
  summaryMetricHelper: {
    ...fontFaces.body.medium,
    marginTop: spacing.xxxs,
    fontSize: fontSizes.sm,
    lineHeight: 17,
    color: colours.textSecondary,
  },
  futureStartHelp: {
    marginTop: spacing.xs,
  },
  summarySectionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  summarySectionCopy: {
    flex: 1,
    minWidth: 0,
  },
  summarySectionKicker: {
    ...fontFaces.heading.semibold,
    fontSize: fontSizes.xs,
    color: colours.textSecondary,
    textTransform: 'uppercase',
  },
  summarySectionTitle: {
    ...fontFaces.heading.bold,
    fontSize: fontSizes.lg,
    lineHeight: 25,
    color: colours.primary,
    marginTop: spacing.xxs,
  },
  summarySectionMeta: {
    ...fontFaces.body.medium,
    fontSize: fontSizes.sm,
    lineHeight: 17,
    color: colours.textSecondary,
    marginTop: spacing.xxs,
  },
  summaryBodyText: {
    ...fontFaces.body.regular,
    fontSize: fontSizes.sm,
    lineHeight: 20,
    color: colours.textSecondary,
  },
  summaryFactGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    rowGap: spacing.sm,
    columnGap: spacing.md,
  },
  summaryFact: {
    flexBasis: '47%',
    flexGrow: 1,
    minWidth: 0,
  },
  summaryFactLabel: {
    ...fontFaces.body.regular,
    fontSize: fontSizes.base,
    lineHeight: 20,
    color: colours.textSecondary,
    marginBottom: spacing.xxxs,
  },
  summaryFactValue: {
    ...fontFaces.heading.semibold,
    fontSize: fontSizes.md,
    lineHeight: 22,
    color: colours.textPrimary,
  },
  summarySourceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colours.borderSoft,
    marginTop: spacing.md,
    paddingTop: spacing.sm,
  },
  summarySourceLabel: {
    ...fontFaces.body.medium,
    fontSize: fontSizes.xs,
    color: colours.textSecondary,
    textTransform: 'uppercase',
  },
  summarySourceValue: {
    flex: 1,
    ...fontFaces.heading.semibold,
    fontSize: fontSizes.sm,
    color: colours.primary,
    textAlign: 'right',
  },
  reconciliationBox: {
    marginTop: spacing.sm,
    borderRadius: radii.input,
    borderWidth: 1,
    borderColor: colours.border,
    backgroundColor: colours.surface,
    padding: spacing.sm,
  },
  reconciliationText: {
    ...fontFaces.heading.semibold,
    fontSize: fontSizes.sm,
    color: colours.textPrimary,
  },
  reconciliationHelp: {
    ...fontFaces.body.regular,
    fontSize: fontSizes.sm,
    lineHeight: 17,
    color: colours.textSecondary,
    marginTop: spacing.xxxs,
  },
  summaryTimelineAction: {
    minHeight: 40,
    paddingHorizontal: 14,
  },
  summaryTimelineList: {
    position: 'relative',
    paddingLeft: 34,
    marginTop: spacing.xs,
  },
  summaryTimelineRail: {
    position: 'absolute',
    left: 11,
    top: 8,
    bottom: 8,
    width: 2,
    backgroundColor: colours.border,
  },
  summaryTimelineRow: {
    minHeight: 58,
    justifyContent: 'center',
    paddingVertical: spacing.xs,
  },
  summaryTimelineNode: {
    position: 'absolute',
    left: -34,
    top: 20,
    width: 24,
    height: 24,
    borderRadius: radii.full,
    borderWidth: 3,
    backgroundColor: colours.background,
  },
  summaryTimelineCopy: {
    minWidth: 0,
  },
  summaryTimelineLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs,
  },
  summaryTimelineLabel: {
    ...fontFaces.heading.semibold,
    fontSize: fontSizes.xs,
    color: colours.textSecondary,
    textTransform: 'uppercase',
  },
  summaryTimelineDates: {
    ...fontFaces.body.medium,
    fontSize: fontSizes.xs,
    color: colours.textSecondary,
    marginTop: spacing.xxxs,
  },
  summaryTimelineTitle: {
    ...fontFaces.heading.bold,
    fontSize: fontSizes.md,
    color: colours.textPrimary,
    marginTop: spacing.xxs,
  },
  summaryTimelineMeta: {
    ...fontFaces.body.regular,
    fontSize: fontSizes.sm,
    color: colours.textSecondary,
    marginTop: spacing.xxxs,
  },
  quickActionsCard: {
    backgroundColor: colours.surfaceMuted,
    borderWidth: 1,
    borderColor: colours.surfaceStrong,
    borderRadius: radii.card,
    marginBottom: spacing.sm,
    marginHorizontal: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
  },
  quickActionsHeader: {
    gap: spacing.xxxs,
  },
  quickActionsRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: spacing.xs,
  },
  quickActionsTitle: {
    ...fontFaces.heading.semibold,
    fontSize: fontSizes.xs,
    color: colours.textSecondary,
    textTransform: 'uppercase',
  },
  quickActionButton: {
    flex: 1,
    minWidth: 0,
    minHeight: 72,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xxs,
  },
  quickActionIcon: {
    width: 48,
    height: 48,
    borderRadius: radii.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colours.surfaceRaised,
    borderWidth: 1,
    borderColor: colours.surfaceStrong,
  },
  quickActionLabel: {
    ...fontFaces.heading.semibold,
    fontSize: fontSizes.sm,
    lineHeight: 17,
    color: colours.textPrimary,
    textAlign: 'center',
  },
  futurePreviewNode: {
    borderColor: colours.border,
  },
  currentPreviewNode: {
    borderColor: colours.teal,
    backgroundColor: colours.white,
  },
  startPreviewNode: {
    borderColor: colours.border,
  },
  timelineAlertBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colours.warningSurface,
    borderRadius: radii.input,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    marginTop: spacing.sm,
  },
  timelineAlertIcon: {
    width: 30,
    height: 30,
    borderRadius: radii.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colours.white,
  },
  timelineAlertCopy: {
    flex: 1,
    minWidth: 0,
  },
  timelineAlertTitle: {
    ...fontFaces.heading.semibold,
    fontSize: fontSizes.sm,
    color: colours.warning,
  },
  timelineAlertBody: {
    ...fontFaces.body.regular,
    fontSize: fontSizes.xs,
    lineHeight: 16,
    color: colours.textSecondary,
    marginTop: spacing.xxxs,
  },
  viewTimelineLink: {
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopWidth: 1,
    borderTopColor: colours.border,
    marginTop: spacing.xs,
  },
  viewTimelineLinkText: {
    ...fontFaces.heading.semibold,
    fontSize: fontSizes.sm,
    color: colours.primary,
  },
  modalScrim: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colours.modalScrim,
  },
  drawer: {
    maxHeight: '84%',
    borderTopLeftRadius: radii.card,
    borderTopRightRadius: radii.card,
    backgroundColor: colours.surfaceRaised,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xl,
  },
  drawerHandle: {
    alignSelf: 'center',
    width: 44,
    height: 4,
    borderRadius: radii.full,
    backgroundColor: colours.borderSoft,
    marginBottom: spacing.md,
  },
  drawerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    marginBottom: spacing.sm,
  },
  drawerTitle: {
    ...fontFaces.heading.bold,
    fontSize: fontSizes.lg,
    color: colours.primary,
  },
  closeText: {
    ...fontFaces.heading.semibold,
    fontSize: fontSizes.sm,
    color: colours.primary,
  },
  drawerOptionList: {
    paddingBottom: spacing.md,
  },
  drawerGroupTitle: {
    ...fontFaces.heading.semibold,
    fontSize: fontSizes.xs,
    color: colours.textSecondary,
    textTransform: 'uppercase',
    marginTop: spacing.md,
    marginBottom: spacing.xs,
  },
  drawerOptionRow: {
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'flex-start',
    borderTopWidth: 1,
    borderTopColor: colours.border,
    paddingVertical: spacing.sm,
  },
  drawerOptionIcon: {
    width: 38,
    height: 38,
    borderRadius: radii.full,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colours.surfaceAccent,
    marginRight: spacing.sm,
    flexShrink: 0,
  },
  drawerOptionIconDanger: {
    backgroundColor: colours.errorSurface,
  },
  drawerOptionCopy: {
    flex: 1,
    minWidth: 0,
    gap: spacing.xxs,
  },
  drawerOptionTitle: {
    ...fontFaces.heading.semibold,
    fontSize: fontSizes.sm,
    color: colours.textPrimary,
  },
  drawerOptionTitleDanger: {
    color: colours.error,
  },
  drawerOptionDescription: {
    ...fontFaces.body.regular,
    fontSize: fontSizes.sm,
    lineHeight: 17,
    color: colours.textSecondary,
  },
  chartCard: {
    marginBottom: 14,
    borderWidth: 1,
    borderColor: colours.border,
  },
  chartHeader: {
    minHeight: 34,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: colours.border,
    paddingBottom: 10,
    marginBottom: 12,
  },
  previewPressed: {
    opacity: 0.84,
  },
  scheduleCard: {
    paddingBottom: 8,
  },
  previewTitle: {
    flex: 1,
  },
  chartActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  fullscreenButton: {
    minHeight: 36,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 14,
    borderRadius: radii.button,
    backgroundColor: colours.white,
    borderWidth: 1,
    borderColor: colours.border,
  },
  fullscreenIconPlaceholder: {
    width: 36,
    height: 36,
    borderRadius: radii.button,
    backgroundColor: colours.surface,
    borderWidth: 1,
    borderColor: colours.border,
  },
  chartSkeleton: {
    minHeight: 196,
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-around',
    overflow: 'hidden',
    borderRadius: radii.input,
    backgroundColor: colours.surface,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.lg,
  },
  skeletonRule: {
    position: 'absolute',
    left: spacing.md,
    right: spacing.md,
    top: '46%',
    height: 1,
    backgroundColor: colours.border,
  },
  skeletonBar: {
    width: 28,
    borderRadius: radii.sm,
    backgroundColor: colours.surfaceStrong,
  },
  skeletonBarTall: {
    height: 132,
  },
  skeletonBarMedium: {
    height: 94,
  },
  skeletonBarShort: {
    height: 58,
  },
  skeletonBarMediumTall: {
    height: 116,
  },
  scheduleSkeleton: {
    minHeight: 226,
    gap: spacing.sm,
    borderRadius: radii.input,
    backgroundColor: colours.surface,
    padding: spacing.md,
  },
  skeletonLine: {
    height: 22,
    borderRadius: radii.sm,
    backgroundColor: colours.surfaceStrong,
  },
  skeletonLineFull: {
    width: '100%',
  },
  skeletonLineMedium: {
    width: '72%',
  },
  skeletonLineShort: {
    width: '48%',
  },
  actionButtonText: {
    textTransform: 'uppercase',
  },
  fullscreenSafe: {
    flex: 1,
    backgroundColor: colours.background,
  },
  fullscreenHeader: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: layout.screenPadding,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colours.border,
    backgroundColor: colours.background,
  },
  closeButton: {
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 14,
    borderRadius: radii.button,
    backgroundColor: colours.surface,
    borderWidth: 1,
    borderColor: colours.border,
  },
  fullscreenBody: {
    flex: 1,
  },
  fullscreenContent: {
    padding: layout.screenPadding,
    paddingBottom: spacing['2xl'],
  },
  timelineSection: {
    marginBottom: spacing.md,
  },
  timelineSectionTitle: {
    color: colours.primary,
    marginBottom: spacing.sm,
  },
  sectionTitle: {
    ...fontFaces.heading.bold,
    fontSize: fontSizes.lg,
    color: colours.primary,
  },
  addActivityButton: {
    minHeight: 40,
    paddingHorizontal: 14,
  },
  eventRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: colours.border,
  },
  eventTitle: {
    ...fontFaces.heading.bold,
    fontSize: fontSizes.sm,
    color: colours.textPrimary,
  },
  eventDate: {
    ...fontFaces.body.regular,
    fontSize: fontSizes.sm,
    lineHeight: 17,
    color: colours.textSecondary,
    marginLeft: spacing.sm,
    maxWidth: 92,
    textAlign: 'right',
  },
  soonerNudgeCard: {
    borderRadius: radii.card,
    borderWidth: 1,
    borderColor: colours.border,
    borderStyle: 'dashed',
    backgroundColor: colours.surface,
    padding: spacing.md,
    marginHorizontal: spacing.sm,
    marginBottom: spacing.sm,
    gap: spacing.sm,
  },
  soonerNudgeInner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  soonerNudgeCopy: {
    flex: 1,
    gap: spacing.xxs,
  },
  soonerCardActive: {
    marginHorizontal: spacing.sm,
    marginBottom: spacing.sm,
    backgroundColor: colours.successSurface,
    borderColor: colours.successBorder,
    gap: spacing.xs,
  },
  // In the summary panel the card is a sibling of the full-width raised panels,
  // so drop the standalone insets and let the panel's gap own the spacing.
  summarySavingsCard: {
    marginHorizontal: 0,
    marginBottom: 0,
  },
  soonerCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  soonerCardTitle: {
    flex: 1,
  },
  soonerSavingsRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    flexWrap: 'wrap',
  },
  soonerMetric: {
    flexBasis: '47%',
    flexGrow: 1,
    minWidth: 0,
    gap: spacing.xxxs,
  },
  soonerManageRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderTopWidth: 1,
    borderTopColor: colours.successBorder,
    paddingTop: spacing.xs,
    marginTop: spacing.xxs,
  },
  overpaymentCard: {
    marginBottom: 14,
    marginHorizontal: spacing.sm,
  },
  overpaymentCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  overpaymentRowLeft: {
    flex: 1,
    minWidth: 0,
  },
  overpaymentCardFooter: {
    borderTopWidth: 1,
    borderTopColor: colours.border,
    paddingTop: spacing.sm,
    marginTop: spacing.xs,
    gap: spacing.xxs,
  },
  overpaymentFooterTotal: {
    ...fontFaces.heading.semibold,
    fontSize: fontSizes.sm,
    color: colours.textPrimary,
  },
  overpaymentFooterSaved: {
    ...fontFaces.heading.semibold,
    fontSize: fontSizes.sm,
    color: colours.secondary,
  },
});
